### ISSUE TITLE
why the class of model's datetime field  is Time class?

### ISSUE THREAD

**Issue by villins** [janko-m/sinatra-activerecord#65]
```
 pry(#<Sinatra::Application>)> Show.last.show_time.class
D, [2016-06-14T18:34:16.605042 #4094] DEBUG -- :   Show Load (0.7ms)  SELECT  `shows`.* FROM `shows`  ORDER BY `shows`.`id` DESC LIMIT 1
=> Time
```
why the class of model's datetime field is Time class, not ActiveSupport::TimeWithZone < Object?

**Comment by janko-m** [comment]
Perhaps this is ActiveRecord's default, and there is a configuration where `ActiveSupport::TimeWithZone` is automatically returned instead of `Time`. However, I don't know ActiveRecord that well to be able to answer that, you should check that with the Rails team, as sinatra-activerecord only helps you setup ActiveRecord, it doesn't affect the behaviour.
